# Generated by Django 5.0.3 on 2024-11-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presentation',
            table='presentations',
        ),
        migrations.AlterModelTable(
            name='presentationuser',
            table='presentation_users',
        ),
        migrations.AlterModelTable(
            name='slide',
            table='slides',
        ),
        migrations.AlterModelTable(
            name='slideelement',
            table='slideelements',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
